# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/AELION/AppData/Local/Temp/lfrEejVTY.ui',
# licensing of 'C:/Users/AELION/AppData/Local/Temp/lfrEejVTY.ui' applies.
#
# Created: Wed Aug  7 14:49:04 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1267, 905)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 1141, 731))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lRech = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lRech.sizePolicy().hasHeightForWidth())
        self.lRech.setSizePolicy(sizePolicy)
        self.lRech.setMinimumSize(QtCore.QSize(75, 0))
        self.lRech.setObjectName("lRech")
        self.horizontalLayout.addWidget(self.lRech)
        self.leRech = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leRech.sizePolicy().hasHeightForWidth())
        self.leRech.setSizePolicy(sizePolicy)
        self.leRech.setMinimumSize(QtCore.QSize(405, 0))
        self.leRech.setObjectName("leRech")
        self.horizontalLayout.addWidget(self.leRech)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lFiltr = QtWidgets.QLabel(self.layoutWidget)
        self.lFiltr.setMinimumSize(QtCore.QSize(75, 0))
        self.lFiltr.setObjectName("lFiltr")
        self.horizontalLayout_2.addWidget(self.lFiltr)
        self.cbPays = QtWidgets.QComboBox(self.layoutWidget)
        self.cbPays.setMinimumSize(QtCore.QSize(120, 0))
        self.cbPays.setObjectName("cbPays")
        self.cbPays.addItem("")
        self.horizontalLayout_2.addWidget(self.cbPays)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cbRegion = QtWidgets.QComboBox(self.layoutWidget)
        self.cbRegion.setMinimumSize(QtCore.QSize(120, 0))
        self.cbRegion.setObjectName("cbRegion")
        self.cbRegion.addItem("")
        self.horizontalLayout_2.addWidget(self.cbRegion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cbNom = QtWidgets.QComboBox(self.layoutWidget)
        self.cbNom.setMinimumSize(QtCore.QSize(120, 0))
        self.cbNom.setObjectName("cbNom")
        self.cbNom.addItem("")
        self.horizontalLayout_2.addWidget(self.cbNom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lRech.setText(QtWidgets.QApplication.translate("MainWindow", "Recherche :", None, -1))
        self.lFiltr.setText(QtWidgets.QApplication.translate("MainWindow", "Filtres :", None, -1))
        self.cbPays.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Tous les pays", None, -1))
        self.cbRegion.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Toutes les régions", None, -1))
        self.cbNom.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Tous les noms", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Consultation", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Réservation", None, -1))

