# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/AELION/AppData/Local/Temp/lfrcVJtNP.ui',
# licensing of 'C:/Users/AELION/AppData/Local/Temp/lfrcVJtNP.ui' applies.
#
# Created: Mon Aug 12 13:56:19 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 905)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1191, 801))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lRech = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lRech.sizePolicy().hasHeightForWidth())
        self.lRech.setSizePolicy(sizePolicy)
        self.lRech.setMinimumSize(QtCore.QSize(75, 0))
        self.lRech.setObjectName("lRech")
        self.horizontalLayout.addWidget(self.lRech)
        self.leRech = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leRech.sizePolicy().hasHeightForWidth())
        self.leRech.setSizePolicy(sizePolicy)
        self.leRech.setMinimumSize(QtCore.QSize(405, 0))
        self.leRech.setObjectName("leRech")
        self.horizontalLayout.addWidget(self.leRech)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lFiltr = QtWidgets.QLabel(self.layoutWidget)
        self.lFiltr.setMinimumSize(QtCore.QSize(75, 0))
        self.lFiltr.setObjectName("lFiltr")
        self.horizontalLayout_2.addWidget(self.lFiltr)
        self.cbPays = QtWidgets.QComboBox(self.layoutWidget)
        self.cbPays.setMinimumSize(QtCore.QSize(120, 0))
        self.cbPays.setObjectName("cbPays")
        self.cbPays.addItem("")
        self.horizontalLayout_2.addWidget(self.cbPays)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cbRegion = QtWidgets.QComboBox(self.layoutWidget)
        self.cbRegion.setMinimumSize(QtCore.QSize(120, 0))
        self.cbRegion.setObjectName("cbRegion")
        self.cbRegion.addItem("")
        self.horizontalLayout_2.addWidget(self.cbRegion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cbNom = QtWidgets.QComboBox(self.layoutWidget)
        self.cbNom.setMinimumSize(QtCore.QSize(120, 0))
        self.cbNom.setObjectName("cbNom")
        self.cbNom.addItem("")
        self.horizontalLayout_2.addWidget(self.cbNom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 1191, 791))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.deDebut = QtWidgets.QDateEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deDebut.sizePolicy().hasHeightForWidth())
        self.deDebut.setSizePolicy(sizePolicy)
        self.deDebut.setCalendarPopup(True)
        self.deDebut.setObjectName("deDebut")
        self.gridLayout.addWidget(self.deDebut, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.deNaissance = QtWidgets.QDateEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deNaissance.sizePolicy().hasHeightForWidth())
        self.deNaissance.setSizePolicy(sizePolicy)
        self.deNaissance.setCalendarPopup(True)
        self.deNaissance.setObjectName("deNaissance")
        self.gridLayout.addWidget(self.deNaissance, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lePrenom = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lePrenom.setObjectName("lePrenom")
        self.gridLayout.addWidget(self.lePrenom, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.cbCentreRes = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbCentreRes.setObjectName("cbCentreRes")
        self.gridLayout.addWidget(self.cbCentreRes, 3, 1, 1, 1)
        self.leNom = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leNom.setObjectName("leNom")
        self.gridLayout.addWidget(self.leNom, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.deFin = QtWidgets.QDateEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deFin.sizePolicy().hasHeightForWidth())
        self.deFin.setSizePolicy(sizePolicy)
        self.deFin.setCalendarPopup(True)
        self.deFin.setObjectName("deFin")
        self.gridLayout.addWidget(self.deFin, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lImage = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lImage.sizePolicy().hasHeightForWidth())
        self.lImage.setSizePolicy(sizePolicy)
        self.lImage.setMinimumSize(QtCore.QSize(0, 450))
        self.lImage.setText("")
        self.lImage.setPixmap(QtGui.QPixmap("img/lfr_small.jpg"))
        self.lImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lImage.setObjectName("lImage")
        self.horizontalLayout_6.addWidget(self.lImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pbValidRes = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbValidRes.setMinimumSize(QtCore.QSize(0, 50))
        self.pbValidRes.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(20)
        self.pbValidRes.setFont(font)
        self.pbValidRes.setFlat(False)
        self.pbValidRes.setObjectName("pbValidRes")
        self.horizontalLayout_7.addWidget(self.pbValidRes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lMsgErr = QtWidgets.QLabel(self.layoutWidget1)
        self.lMsgErr.setAutoFillBackground(False)
        self.lMsgErr.setText("")
        self.lMsgErr.setAlignment(QtCore.Qt.AlignCenter)
        self.lMsgErr.setObjectName("lMsgErr")
        self.horizontalLayout_8.addWidget(self.lMsgErr)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Centres de vacances - La Frite Rose", None, -1))
        self.lRech.setText(QtWidgets.QApplication.translate("MainWindow", "Recherche :", None, -1))
        self.lFiltr.setText(QtWidgets.QApplication.translate("MainWindow", "Filtres :", None, -1))
        self.cbPays.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Tous les pays", None, -1))
        self.cbRegion.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Toutes les régions", None, -1))
        self.cbNom.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Tous les noms", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Consultation", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Date de début", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Prénom", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Nom", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Centre de vacances", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Date de naissance", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Date de fin", None, -1))
        self.pbValidRes.setText(QtWidgets.QApplication.translate("MainWindow", "Je valide mon inscription", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Réservation", None, -1))

